name: FOnline Roleplay
description: >
    Heavy roleplay oriented FOnline SDK v476 build.
about: >
    FOnline Roleplay Website.

master_repo: false
# url: "/"
markdown: kramdown
highlighter: rouge

gems: ['jekyll-paginate', 'jekyll-gist', 'jekyll-feed']

paginate: 4

logo:             logo.png
disqus_shortname:

rtl: false
owner:
  name:           erandelax
  avatar:         "https://www.gravatar.com/avatar/45143ff0b6a22225510b786f471b4eec?s=256"
  email:          "erandelax@gmail.com"
  # Social networking links used in footer. Update and remove as you like.
  discord:        "https://discord.gg/sFkCj5F"
