name: FOnline Roleplay
description: >
    FOnline Roleplay
about: >
    Heavy roleplay oriented FOnline SDK v476 build
permalink: /:categories/:title

master_repo: false
#url: "/fonline-roleplay-server"
markdown: redcarpet
redcarpet:
  extensions: ["tables", "fenced_code_blocks","strikethrough","autolink"]
highlighter: rouge

gems: ['jekyll-paginate', 'jekyll-gist', 'jekyll-feed']

paginate: 10

logo:             logo.png
disqus_shortname:

rtl: false
owner:
  name:           erandelax
  avatar:         "https://www.gravatar.com/avatar/45143ff0b6a22225510b786f471b4eec?s=256"
  email:          "erandelax@gmail.com"
  # Social networking links used in footer. Update and remove as you like.
  discord:        "https://discord.gg/sFkCj5F"
